# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: name-tests-test
        name: Tests should be named test_*.py
        args: ["--pytest-test-first"]

  - repo: https://github.com/pycqa/isort
    rev: 5.11.2
    hooks:
      - id: isort

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [ "--py310-plus" ]

  - repo: https://github.com/PyCQA/docformatter
    rev: v1.5.1
    hooks:
      - id: docformatter

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        # It is recommended to specify the latest version of Python
        # supported by your project here, or alternatively use
        # pre-commit's default_language_version, see
        # https://pre-commit.com/#top_level-default_language_version
        #language_version: python3.9

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991 # Use the sha / tag you want to point at
    hooks:
      - id: mypy
