name: PyTest

on: push

jobs:
  pytest:
    needs: pre-commit

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Read .pre-commit-config.yaml
        uses: pietrobolcato/action-read-yaml@1.0.0
        id: read_action_js
        with:
          config: ${{ github.workspace }}/.pre-commit-config.yaml

      - name: Install poetry
        run: |
          echo poetry version: ${{ steps.read_action_js.outputs["repos.-1.rev"] }}
          pipx install poetry==${{ steps.read_action_js.outputs["repos.-1.rev"] }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - run: poetry install

      - run: poetry run pytest
