name: Python

on:
  pull_request:
    branches: [main]

env:
  # renovate: datasource=github-releases depName=python-poetry/poetry
  POETRY_VERSION: "1.8.3"

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GIT_AUTO_COMMIT_ACTION_CHECKOUT_PAT }}

      - name: Install poetry
        run: pipx install poetry=="${{ env.POETRY_VERSION }}"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - run: poetry install

      - name: Get pre-commit version
        id: pre-commit-version
        run: |
          echo "pre-commit-version=$(poetry run pre-commit -V)" >> $GITHUB_OUTPUT

      - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ steps.pre-commit-version.outputs.pre-commit-version }}|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - run: poetry run pre-commit run --show-diff-on-failure --color=always --all-files

      - uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5
        if: success() || failure()
        with:
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          commit_message: "chore(pre-commit): apply automatic changes"

  pytest:
    needs: pre-commit

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Read .pre-commit-config.yaml
        uses: actions-tools/yaml-outputs@1a26d8aaa36aa54fe71d91c265dd6d4369a4fcfb # v2
        with:
          file-path: ${{ github.workspace }}/.pre-commit-config.yaml
          node: repos.10

      - name: Install poetry
        run: pipx install poetry=="${{ env.POETRY_VERSION }}"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - run: poetry install

      - run: poetry run pytest ${{ github.workspace }}/tests
