name: Python

on: push

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GIT_AUTO_COMMIT_ACTION_CHECKOUT_PAT }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: pre-commit/action@v3.0.0

      - uses: stefanzweifel/git-auto-commit-action@v5
        if: success() || failure()
        with:
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          commit_message: "chore(pre-commit): apply automatic changes"

  pytest:
    needs: pre-commit

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Read .pre-commit-config.yaml
        uses: actions-tools/yaml-outputs@v2
        with:
          file-path: ${{ github.workspace }}/.pre-commit-config.yaml
          node: repos.10

      - name: Install poetry
        run: pipx install poetry==${{ env.rev }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - run: poetry install

      - run: poetry run pytest ${{ github.workspace }}/tests
